security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\Utilisateur:
            algorithm: auto
    providers:
        users_in_memory: { memory: null }
        in_database: 
            entity:
                class: App\Entity\Utilisateur
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: in_database

            form_login:
                login_path: connexion
                check_path: connexion
                always_use_default_target_path: true
                default_target_path: /chemin

            logout:
                path: logout
                target: connexion

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: '^/inscriptionProf', roles: ROLE_SUPER_ADMIN}
         - { path: '^/editS/{id}', roles: ROLE_SUPER_ADMIN}
         - { path: '^/domaine', roles: ROLE_SUPER_ADMIN}
         - { path: '^/consulteBDD', roles: ROLE_SUPER_ADMIN}
         - { path: '^/editJ/{id}', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN]}
         - { path: '^/editP/{id}', roles: [ROLE_SUPER_ADMIN,ROLE_USER]}
         - { path: '^/chemin', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN,ROLE_USER]}
         - { path: '^/question', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN]}
         - { path: '^/question/{id}/edit', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN]}
         - { path: '^/question/{id}', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN]}
         - { path: '^/profil', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN]}
         - { path: '^/maraudeur', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN,ROLE_USER]}
         - { path: '^//combat/{id}', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN,ROLE_USER]}
         - { path: '^/get/question/{id}', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN,ROLE_USER]}
         - { path: '^/post/question', roles: [ROLE_SUPER_ADMIN,ROLE_ADMIN,ROLE_USER]}

         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/profile, roles: [ROLE_USER,ROLE_ADMIN] }
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN